In [1]:
import numpy as np
import pandas as pd
from numpy.random import default_rng
from typing import Optional

from sklearn.linear_model import RidgeCV, LassoCV
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from statsmodels.tsa.stattools import adfuller

In [2]:
bjair=pd.read_csv('Beijing_air_Tiantan_data.csv')

In [3]:
bjair.head()

No  year  month  day  hour  PM2.5  PM10  SO2   NO2     CO    O3  TEMP   
0   1  2013      3    1     0    6.0   6.0  4.0   8.0  300.0  81.0  -0.5  \
1   2  2013      3    1     1    6.0  29.0  5.0   9.0  300.0  80.0  -0.7   
2   3  2013      3    1     2    6.0   6.0  4.0  12.0  300.0  75.0  -1.2   
3   4  2013      3    1     3    6.0   6.0  4.0  12.0  300.0  74.0  -1.4   
4   5  2013      3    1     4    5.0   5.0  7.0  15.0  400.0  70.0  -1.9   

     PRES  DEWP  RAIN   wd  WSPM  station  
0  1024.5 -21.4   0.0  NNW   5.7  Tiantan  
1  1025.1 -22.1   0.0   NW   3.9  Tiantan  
2  1025.3 -24.6   0.0  NNW   5.3  Tiantan  
3  1026.2 -25.5   0.0    N   4.9  Tiantan  
4  1027.1 -24.5   0.0  NNW   3.2  Tiantan

In [5]:
bjair.dropna(inplace=True)

In [6]:
adfuller(bjair['PM2.5'])

(-18.973860007018498,
 0.0,
 48,
 32794,
 {'1%': -3.4305494209896863,
  '5%': -2.861628138962805,
  '10%': -2.566816913632247},
 287482.854285711)

In [7]:
adfuller(bjair['PM10'])

(-21.79085147300261,
 0.0,
 24,
 32818,
 {'1%': -3.4305492751405127,
  '5%': -2.8616280745033746,
  '10%': -2.566816879322118},
 320237.26044401235)

In [8]:
adfuller(bjair['TEMP'])

(-3.6977043247029773,
 0.00414556098558455,
 51,
 32791,
 {'1%': -3.430549439235846,
  '5%': -2.8616281470268685,
  '10%': -2.566816917924545},
 92814.68864388712)

In [3]:
%pip install Tushare

Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 978.4 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 37.6 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.9/137.9 kB 11.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 kB 16.4 MB/s eta 0:00:00
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1257 sha256=a000eca3c8df5333bb5db37a0c21a3bffa50283d4414c9c49a8bcf2543665e82
  Stored in directory: /home/ec2-user/.cache/pip/wheels/25/42/45/b773edc52acb16cd2db4cf1a0b47117e2f69bb4eb300ed0e70
Successfully built bs4
  Attempting uninstall: websocket-client
    Found existing installation: websocket-client 1.5.1
    Uninstalling websocket-client-1.5.1:
      Successfully uninstalled websocket-client-1.5.1
ERROR: pip's dependency resolver does not currently take in

In [2]:
#Import and Set Token
import tushare as ts
#Given token
ts.set_token('756a1f4aba6dd90ced168a81497f46697c8499ccfa76b317daf6e874')

#my token
#ts.set_token('01f4d5ecf2049e20cfa55f771e857249af7d8a9eea17fa9c74b6e690')
#Initialize api
pro = ts.pro_api()

ModuleNotFoundError: No module named 'tushare'

In [5]:
data=pro.fund_daily(ts_code='562930.SH')

In [15]:
adfuller(data['close']) #Non-stationary

(-1.5099282229902748,
 0.5285943967075033,
 0,
 47,
 {'1%': -3.5778480370438146,
  '5%': -2.925338105429433,
  '10%': -2.6007735310095064},
 -174.26317227656148)

# Stationarize (Transformation then deseaonalize)

## Log-transformation

In [16]:
log_price=np.log(data['close'])
adfuller(log_price)

(-1.489145635206965,
 0.538873841604416,
 0,
 47,
 {'1%': -3.5778480370438146,
  '5%': -2.925338105429433,
  '10%': -2.6007735310095064},
 -176.8164609368891)

## Box-Cox Transformation

In [6]:
from scipy import stats
box_data, box_lambda=stats.boxcox(data['close'])

In [19]:
adfuller(box_data)

(-1.5466986885460778,
 0.510296820873596,
 0,
 47,
 {'1%': -3.5778480370438146,
  '5%': -2.925338105429433,
  '10%': -2.6007735310095064},
 -178.0512876102752)

In [23]:
box_data

array([-0.06946808, -0.03890463, -0.03890463, -0.02828786, -0.02085717,
       -0.01847585, -0.04453748, -0.05190221, -0.05650146, -0.05190221,
       -0.05806562, -0.1089914 , -0.09100528, -0.05495295, -0.09879322,
       -0.09485916, -0.09292231, -0.04453748, -0.05190221, -0.02828786,
       -0.02451778, -0.05190221, -0.06448236, -0.03086386, -0.03349122,
       -0.02701878, -0.01160453, -0.0138505 ,  0.00488201, -0.00201935,
        0.00770109,  0.00953618,  0.008623  ,  0.03328723,  0.03049153,
        0.06462991,  0.07996212,  0.06621721,  0.05580017,  0.03729189,
        0.04695527,  0.04582286,  0.0214527 ,  0.01310334, -0.00304369,
        0.00770109, -0.00512223,  0.02534222])

In [7]:
date=pd.to_datetime(data['trade_date'])
box_price=pd.Series(box_data, index=date, name='box_cox_price')
box_price.head()

trade_date
2023-08-11   -0.069468
2023-08-10   -0.038905
2023-08-09   -0.038905
2023-08-08   -0.028288
2023-08-07   -0.020857
Name: box_cox_price, dtype: float64

In [38]:
box_price

trade_date
2023-08-11   -0.069468
2023-08-10   -0.038905
2023-08-09   -0.038905
2023-08-08   -0.028288
2023-08-07   -0.020857
2023-08-04   -0.018476
2023-08-03   -0.044537
2023-08-02   -0.051902
2023-08-01   -0.056501
2023-07-31   -0.051902
2023-07-28   -0.058066
2023-07-27   -0.108991
2023-07-26   -0.091005
2023-07-25   -0.054953
2023-07-24   -0.098793
2023-07-21   -0.094859
2023-07-20   -0.092922
2023-07-19   -0.044537
2023-07-18   -0.051902
2023-07-17   -0.028288
2023-07-14   -0.024518
2023-07-13   -0.051902
2023-07-12   -0.064482
2023-07-11   -0.030864
2023-07-10   -0.033491
2023-07-07   -0.027019
2023-07-06   -0.011605
2023-07-05   -0.013851
2023-07-04    0.004882
2023-07-03   -0.002019
2023-06-30    0.007701
2023-06-29    0.009536
2023-06-28    0.008623
2023-06-27    0.033287
2023-06-26    0.030492
2023-06-21    0.064630
2023-06-20    0.079962
2023-06-19    0.066217
2023-06-16    0.055800
2023-06-15    0.037292
2023-06-14    0.046955
2023-06-13    0.045823
2023-06-12    0.021453


## STL

In [8]:
from statsmodels.tsa.seasonal import STL
stl_model=STL(box_data, period=12, seasonal=13)
res=stl_model.fit()

In [10]:
res.seasonal

array([-0.04765821, -0.00570038, -0.01783073, -0.00389845,  0.00316366,
        0.02468428,  0.00923882,  0.01546676,  0.01678621,  0.00931732,
        0.00221178, -0.02505068, -0.02139015,  0.00206302, -0.0088266 ,
       -0.00565896,  0.00235771,  0.01604507,  0.00248934,  0.00556943,
        0.00231083,  0.00103377, -0.0077361 , -0.00914336,  0.00537194,
        0.01013499,  0.00060752, -0.00690931,  0.00218213,  0.00801477,
       -0.00442625, -0.00477441, -0.01272473, -0.00753679, -0.01782867,
        0.00542907,  0.03238281,  0.01800284,  0.0108443 , -0.00727439,
        0.00319634,  0.00028881, -0.01161695, -0.01602415, -0.02880284,
       -0.01612468, -0.02759272,  0.01877222])

In [11]:
res.trend

array([-0.02028172, -0.02502181, -0.02971662, -0.03434548, -0.0388917 ,
       -0.04334936, -0.04772986, -0.05206263, -0.05640211, -0.06084077,
       -0.06544508, -0.06804877, -0.06919746, -0.06898333, -0.06775666,
       -0.06584593, -0.06352114, -0.06088097, -0.057738  , -0.05385912,
       -0.04920057, -0.04395073, -0.03830199, -0.03255463, -0.02698524,
       -0.02154786, -0.01595183, -0.0098377 , -0.00315433,  0.00388678,
        0.01085691,  0.0173475 ,  0.02319603,  0.02836329,  0.03270598,
        0.03617644,  0.03877568,  0.04041204,  0.03924866,  0.03769273,
        0.03601518,  0.034224  ,  0.03231064,  0.03026901,  0.02809746,
        0.02579774,  0.02337414,  0.02083233])

In [14]:
adfuller(res.resid)

(-4.372956640903829,
 0.00033130929768299247,
 0,
 47,
 {'1%': -3.5778480370438146,
  '5%': -2.925338105429433,
  '10%': -2.6007735310095064},
 -218.5228386273601)

## Differencing

In [16]:
box_price_diff=box_price.diff(periods=12)

In [18]:
adfuller(box_price_diff.dropna())

(-1.5804379993237234,
 0.4934122530617333,
 0,
 35,
 {'1%': -3.6327426647230316,
  '5%': -2.9485102040816327,
  '10%': -2.6130173469387756},
 -102.61936329665099)